---
###tasks file for replication-role

- name: 03 Create-user repication mode
  ansible.builtin.include_tasks:
    03.create-user.yml
  tags: createUser

- name: 04 Update template from local to srv
  ansible.builtin.include_tasks:
    04.update-config.yml

- name: 05 Check if postgresql is initialized
  ansible.builtin.include_tasks:
    05.check_postgresql.yml

# - name: Check if postgresql is initialized
#   ansible.builtin.stat:
#     path: "{{ postgresql_data_dir }}/pg_hba.conf"
#   register: postgres_data
#   notify:
#     - Stop Postgresql

# - name: Empty data dir
#   ansible.builtin.file:
#     path: "{{ postgresql_data_dir }}"
#     state: absent
#   when: not postgres_data.stat.exists

# - name: Initialize PostgreSql
#   ansible.builtin.shell: "{{ postgresql_bin_path }}/initdb -D {{ postgresql_data_dir }}"
#   become: true
#   become_user: postgres
#   when: not postgres_data.stat.exists
