---
# handlers file for standalone-role
- name: Restart Postgresql
  ansible.builtin.systemd:
    name: postgresql
    state: restarted

- name: Start Postgresql
  ansible.builtin.systemd:
    name: postgresql
    state: started

- name: Stop Postgresql
  ansible.builtin.systemd:
    name: postgresql
    state: stopped

- name: Enable Postgresql
  ansible.builtin.systemd:
    name: postgresql
    enabled: true

- name: Start and enable service
  ansible.builtin.service:
    name: postgresql
    state: started
    enabled: true