---
# 04 update config file
- name: 04 Copy template tu file len server
  ansible.builtin.template:
    src: pg_hba.conf.j2
    dest: /tmp/pg_hba.conf
    backup: true
  # notify:
  #   - Stop Postgresql
